team-charls/charls

test/main.cpp
Encoding to / decoding from PNM now supports also 16bit depth RGB images.
=> PNM (En)(De)code bug fixed

src/CMakeLists.txt
This PR adds the public headers to the CMake install target, and updates the install target for all configurations.
This modification makes it easier to consume the library on Linux platforms, and to support 3rd party package managers such as conan.
=> Add public headers to install target

src/CMakeLists.txt
This PR includes a small change to the src/CMakeLists.txt file such that charls header files can be more easily imported by projects that use charls as a cmake sub project.  With this change, a parent project can do:
#include <charls/charls.h>
rather than something like:
#include "../extern/charls/include/charls/charls.h"
Would be nice to have @malaterre review
=> Improve support for cmake sub projects

src/CMakeLists.txt
This PR adds an additional feature to the cmake.
If you apply the changes of the PR, you get the file `charlsConfig.cmake` with the `install` command which allows you to use `find_package(charls CONFIG)`.
=> Install charlsConfig.cmake

include/charls/charls_jpegls_decoder.h, samples/convert.c/main.c, samples/convert.cpp/main.cpp, src/charls_jpegls_encoder.cpp, src/jpeg_stream_reader.cpp, src/jpeg_stream_reader.h, src/util.h, unittest/jpeg_stream_reader_test.cpp, unittest/jpegls_encoder_test.cpp
If component count is 1 then only interleave mode none may be used.
Validate this during encoding and decoding.
=> Validate interleave mode against component count

include/charls/public_types.h, src/charls_jpegls_decoder.cpp, src/decoder_strategy.h, src/jpeg_stream_reader.cpp, src/jpeg_stream_reader.h, src/jpegls_error.cpp, unittest/jpeg_stream_reader_test.cpp, unittest/jpegls_decoder_test.cpp
Every valid JPEG-LS bit stream has an End-Of-Image (EOI) marker at the end. Add a test to ensure CharLS throw if this marker is missing.
Also prevent that during decoding CharLS doesn't read out of bounds.
=> Improve missing EOI marker handling

include/charls/charls_jpegls_decoder.h, include/charls/charls_jpegls_encoder.h, include/charls/public_types.h, src/charls_jpegls_encoder.cpp, src/jpeg_stream_reader.cpp, src/jpeg_stream_writer.cpp, src/jpeg_stream_writer.h, src/jpegls_error.cpp, src/util.h, src/version.cpp, unittest/CharLSUnitTest.vcxproj, unittest/CharLSUnitTest.vcxproj.filters, unittest/golomb_table_test.cpp, unittest/jpeg_stream_reader_test.cpp, unittest/jpeg_stream_writer_test.cpp, unittest/jpegls_encoder_test.cpp, unittest/jpegls_preset_coding_parameters_test.cpp, unittest/jpegls_preset_coding_parameters_test.h
Extend the functionality of the encoder with 3 boolean options:
1) An option to ensure that the generated output is always even: copy output into DICOM file scenario.
2) An option to write the version number as COM segment: allows tracking which encoder version was used.
3) An option to write always the pc_parameters for bit per sample > 12: needed for Java JAI JPEG-LS decoder
(this option is on by default for 2.x).
=> Add support to set special options for the encoder

CMakeLists.txt, Directory.Build.props, doc/style_and_design.md, fuzztest/main.cpp
Reserve the usage of Weverything and EnableAllWarnings for interactive development.
=> Update warnings used by Clang and MSVC

include/charls/charls_jpegls_decoder.h, include/charls/charls_jpegls_encoder.h, test/performance.cpp, unittest/jpegls_decoder_test.cpp
- Add missing API docs
- std::vector perform an initialization when its size is resized. This has a significant impact
on the performance measurements. Ensure that this step is done outside the timed loop.
=> Improve API docs and decode perf measurement

CMakeLists.txt, src/util.h
When CHARLS_CHECK_RETURN is expanded to [[noignore]] is needs to before inline
=> Ensure CHARLS_CHECK_RETURN is the first statement

README.md, include/charls/public_types.h, src/charls_jpegls_decoder.cpp, src/charls_jpegls_encoder.cpp, src/constants.h, src/jpeg_stream_reader.cpp, src/jpeg_stream_reader.h, src/jpeg_stream_writer.cpp, src/jpeg_stream_writer.h, src/jpegls_error.cpp, src/jpegls_preset_parameters_type.h, unittest/jpeg_stream_writer_test.cpp, unittest/jpeg_test_stream_writer.h, unittest/jpegls_decoder_test.cpp, unittest/jpegls_encoder_test.cpp
Remove the limit that height\width needs to be in the range [1, 65535].
=> Add support to encode\decode oversized images

.gitignore, src/CMakeLists.txt, src/charls_jpegls_decoder.cpp
The shared library build with GCC (tested version 11.20) becomes smaller and faster.
=> Enable IPO (LTO) for GCC builds

azure-pipelines.yml
Visual Studio 2017 will be phased out. Replace VS 2017 with VS 2022 on the Azure Devops CI build.
Note: VS 2017 and VS 2015 are still supported compilers.
=> Replace Visual Studio 2017 with 2022 on CI build

README.md
sample-mapping procedure is JPEG-LS specific, clarify limitation for palletized images.
=> Clarify limitation for palette color

benchmark/benchmark.vcxproj, benchmark/benchmark.vcxproj.filters, benchmark/context_regular_mode.cpp, benchmark/context_regular_mode_v220.h, doc/style_and_design.md, src/CMakeLists.txt, src/CharLS.vcxproj, src/CharLS.vcxproj.filters, src/constants.h, src/context.h, src/context_regular_mode.h, src/context_run_mode.h, src/scan.h, unittest/CharLSUnitTest.vcxproj, unittest/CharLSUnitTest.vcxproj.filters, unittest/context_run_mode_test.cpp
- Use standard C++, the compiler will take of using the optimal registers.
- Use uint32_t instead of uint16_t (slightly faster)
=> Benchmark the update_variables for context

CharLS.sln.DotSettings, src/charls_jpegls_encoder.cpp, src/jpegls.cpp, src/jpegls_preset_coding_parameters.h, src/util.h, unittest/jpegls_encoder_test.cpp, unittest/jpegls_preset_coding_parameters_test.cpp
The JPEG-LS standard allow it to write 0 values in the LSE segment to indicate that the default value should be used. By writing always the actual values (if not default) the decoding always use the same values as the encoding.
=> Write full coding parameters when not default

CMakeLists.txt, fuzztest/main.cpp, src/jpegls_preset_coding_parameters.h
- /permissive- is supported since Visual Studio 2017.
- VS 2015 cannot handle all constexpr functions with mutiple return statements.
- VS 2015 template deduction is limited.
=> Restore Visual Studio 2015 compatibility

src/jpeg_stream_reader.cpp, src/jpeg_stream_reader.h
Ensure that that all functions in the jpeg_stream_reader and the jpeg_stream_writer that read or write a segment use identical names when possible.
=> Sync function names that read a marker segment

benchmark/benchmark.vcxproj, benchmark/benchmark.vcxproj.filters, benchmark/log2.cpp, src/default_traits.h, src/util.h, test/main.cpp, unittest/CharLSUnitTest.vcxproj, unittest/CharLSUnitTest.vcxproj.filters, unittest/jpegls_decoder_test.cpp, unittest/pch.h, unittest/util_test.cpp
- Rename the log_2 function into log2_ceil as that is what the function performs.
- Add unit test and benchmark test to get insight if using it in more places has benefits.
=> Add unit test and benchmark for log2_ceil

cpp.hint, src/charls_jpegls_decoder.cpp, src/charls_jpegls_encoder.cpp, src/jls_codec_factory.h, src/util.h, unittest/jpeg_stream_writer_test.cpp, unittest/jpegls_encoder_test.cpp, unittest/util_test.cpp
As CharLS now supports oversized image dimensions, the x86 build should check that the calculated estimated destination buffer size doesn't overflow.
=> Add overflow detection for estimated_destination_size in x86 build

CHANGELOG.md, SECURITY.md, include/charls/charls_jpegls_decoder.h, include/charls/charls_jpegls_encoder.h, include/charls/version.h, unittest/jpegls_decoder_test.cpp, unittest/jpegls_encoder_test.cpp
STL containers have the ::value_type typedef. Use this as simple SFINAE check to
ensure API methods that should be used with an STL like container are only available
if a container is passed.
This prevents ambiguous overload problems.
There are more advanced solutions: is_container in Boost, Concepts in C++20. but for the C++ API this solution meets its purpose (and is supported on older compilers).
=> Use SFINAE on Container::value_type to prevent ambiguous overloads

src/CMakeLists.txt
Set VISIBILITY_INLINES_HIDDEN to 1 so that -fvisibility-inlines-hidden
is also passed on the gcc command line (-fvisibility=hidden is passed
thanks to CXX_VISIBILITY_PRESET).
At least on Debian system this allow hidding of c++ symbol:
% c++filt _ZnwmPv
operator new(unsigned long, void*)
=> Setup VISIBILITY_INLINES_HIDDEN cmake property on charls target

CMakeLists.txt, src/CMakeLists.txt
Per cmake documentation:
* https://cmake.org/cmake/help/git-stage/manual/cmake-compile-features.7.html#requiring-language-standards
For example, if C++ 11 features are used extensively in a project's
header files, then clients must use a compiler mode that is no less than
C++ 11. This can be requested with the code:
target_compile_features(mylib PUBLIC cxx_std_11)
In this example, CMake will ensure the compiler is invoked in a mode of
at-least C++ 11 (or C++ 14, C++ 17, ...), adding flags such as
-std=gnu++11 if necessary. This applies to sources within mylib as well
as any dependents (that may include headers from mylib).
=> Do not enforce exactly c++14 standard when building charls

CMakeLists.txt, src/color_transform.h, test/performance.cpp, unittest/util.cpp
CharLS is cross-platform. -Wcast-align=strict will always warn for alignement issues, even when current platform can handle it (for example x86)
Use void*+static_cast to increase alignement of dynamic allocated memory.
=> Enable -Wcast-align=strict and use void+static_cast

include/charls/public_types.h
This should help user write shorter code:
encoding_option |= encoding_options::even_destination_size;
=> Add a bitwise OR assigment operator for encoding_options

include/charls/annotations.h, include/charls/charls_jpegls_decoder.h, include/charls/charls_jpegls_encoder.h, include/charls/public_types.h, src/charls_jpegls_decoder.cpp, src/charls_jpegls_encoder.cpp, src/constants.h, src/jpeg_stream_reader.cpp, src/jpeg_stream_reader.h, src/jpeg_stream_writer.cpp, src/jpeg_stream_writer.h, src/util.h, unittest/charls_jpegls_decoder_test.cpp, unittest/charls_jpegls_encoder_test.cpp, unittest/jpeg_stream_reader_test.cpp, unittest/jpegls_decoder_test.cpp, unittest/jpegls_encoder_test.cpp
APPn markers are application specific markers. They can be used to store additional information in the JPEG-LS byte stream. Until know it was not possible to add these kind of markers from "user" code or get a notification when such a marker was present in the JPEG-LS stream.
=> Add support to write and read APPn markers

include/charls/charls_jpegls_encoder.h
This should fix the following compilation error on gcc-10:
In file included from charls/src/charls_jpegls_encoder.cpp:4:
charls/include/charls/charls_jpegls_encoder.h:520:119: error: attribute ‘access(read_only, 2, 3)’ positional argument 1 references non-pointer argument type ‘int32_t’ {aka ‘int’}
520 |                                            CHARLS_IN_READS_BYTES(size) const void* application_data, const size_t size)
|
=> Fix off-by-one function attribute declaration

azure-pipelines.yml
The latest CI build agent also supports GCC 10. Update one of the build configurations to use GCC 10 to get beter compiler coverage.
=> Use GCC 10 on the CI server

src/charls_jpegls_encoder.cpp
This will be consistent with the ordering of the new API introduced in
commit 8225d16 where APPx markers can only be inserted before SOF55.
=> Switch order of APP8 and SOF55

include/charls/annotations.h, include/charls/charls_jpegls_decoder.h, include/charls/public_types.h, include/charls/validate_spiff_header.h, src/CMakeLists.txt, src/CharLS.vcxproj, src/CharLS.vcxproj.filters, src/jpegls_error.cpp, src/validate_spiff_header.cpp, unittest/CharLSUnitTest.vcxproj, unittest/CharLSUnitTest.vcxproj.filters, unittest/jpegls_decoder_test.cpp, unittest/util.cpp, unittest/util.h, unittest/validate_spiff_header_test.cpp
To ensure that the SPIFF header (when present) is valid validate the properties of the header. This can only be done after the frame info is also available.
=> Add method to validate SPIFF header

include/charls/validate_spiff_header.h, unittest/validate_spiff_header_test.cpp
The original PR didn't add XML documentation.
=> Add documentation to charls_validate_spiff_header method

include/charls/charls_jpegls_encoder.h, src/charls_jpegls_encoder.cpp, unittest/charls_jpegls_encoder_test.cpp, unittest/jpegls_encoder_test.cpp
This helper function can be used to add SPIFF headers to existing JPEG-LS streams.
=> Add method write_spiff_end_of_directory_entry

include/charls/charls_jpegls_encoder.h, include/charls/public_types.h, src/charls_jpegls_decoder.cpp
- Using a private namespace makes it possible to prevent that the helper functions are in the charls namespace.
- As encoding_options is used as a flag enum it makes more sense to use an unsigned type (with well defined behaviour for bitwise operations)
- Using the same type helps ReSharper to match the definition and the implementation
=> Move enum encoding_options in its own private namespace

include/charls/public_types.h
To be able to export from a header unit, inline is needed. C++14 doesn't support it however.
=> Add inline to constexpr for compatibility with C++20

Directory.Build.props, benchmark/benchmark.cpp, fuzztest/main.cpp, include/charls/charls_jpegls_decoder.h, samples/convert.cpp/main.cpp, test/bitstreamdamage.cpp, test/main.cpp, test/util.cpp, test/util.h, unittest/CharLSUnitTest.vcxproj, unittest/encoder_strategy_test.cpp, unittest/jpeg_stream_reader_test.cpp, unittest/jpeg_stream_writer_test.cpp, unittest/jpegls_decoder_test.cpp, unittest/jpegls_encoder_test.cpp
The destructor of std::ofstream will close the stream, but not report any failures (by design). Call close to trigger an exception when the close fails.
static_cast for constant values can be replaced with uniform initialization, this allows to reduce the number of static_casts.
Change the bin+intermediate to be sub-directories of build for MSBuild builds. This makes it easier to clean.
=> Use explicit ofstream.close() and replace static_casts

CHANGELOG.md, src/jpeg_stream_reader.cpp, unittest/interface_test.cpp, unittest/jpegls_decoder_test.cpp, unittest/util.cpp, unittest/util.h
The bytes_per_plane value was using the default stride and not the passed custom stride. For multi component images with interleave mode none this caused the second plane to overwrite part of the first decoded plane, etc.
Also added a check to verify the passed stride argument, it should minimal be the default stride.
=> Fix the incorrect computation for bytes_per_plane if custom stride is used

CMakeLists.txt, src/jls_codec_factory.h, unittest/color_transform_test.cpp, unittest/jpeg_stream_reader_test.cpp, unittest/jpeg_stream_writer_test.cpp, unittest/jpegls_decoder_test.cpp, unittest/jpegls_encoder_test.cpp
CharLS is designed to throw when a method fails. End all unit test that verify this behaviour with _throws at the end.
=> Add _throws to unit tests that verify failures

benchmark/benchmark.cpp, benchmark/context_regular_mode_v220.h, benchmark/log2.cpp, fuzztest/main.cpp, samples/convert.cpp/main.cpp, src/charls_jpegls_encoder.cpp, src/jpeg_stream_reader.cpp, test/main.cpp, test/util.cpp, unittest/jpeg_stream_reader_test.cpp, unittest/jpegls_decoder_test.cpp
CharLS doesn't support mixing interleave modes.
Add a unit test to ensure that CharLS will throw a not supported exception. The actual checking was already done.
Note: also resolve some static analyzer warnings, reported with the latest version of ReSharper\clang-tidy.
=> Add a unit test for unsupported mixed interleave modes

unittest/golomb_table_test.cpp, unittest/jpeg_stream_writer_test.cpp
MSVC 2022 17.5.0 Preview 1.0 has improved warning C26496 detection, resolve the report warning.
=> Resolve MSVC warning C26496

CMakeLists.txt, src/color_transform.h, src/context_run_mode.h, src/process_line.h, test/portable_anymap_file.h
-Wconversion will warn when implicit conversion may cause data loss.
=> Add -Wconversion to GCC and clang as compiler option

.clang-tidy, .github/workflows/build.yml, .github/workflows/codeql-analysis.yml, CHANGELOG.md, CMakeLists.txt, Directory.Build.props, README.md, doc/style_and_design.md, include/charls/annotations.h, include/charls/version.h, src/CMakeLists.txt, src/CharLS.vcxproj, src/byte_span.h, src/util.h, src/version.cpp
The release of C++17 has been 5 years ago. The supported period of C++14 has ended and the minimum required C++ version will be increased to C++17 for building the library and using it.
=> Update version to 3.0.0 and minimum C++ version to 17

include/charls/annotations.h, include/charls/charls_jpegls_decoder.h, include/charls/charls_jpegls_encoder.h, include/charls/jpegls_error.h, src/byte_span.h, src/jpeg_stream_reader.cpp, src/jpeg_stream_reader.h, src/util.h
C++17 always provide the standard [[nodiscard]] attribute
Use this attribute when compiling in C++ mode. Code that also can be used in C mode still needs to use CHARLS_CHECK_RETURN. C23 will also provide the attribute [[nodiscard]].
=> Replace CHARLS_CHECK_RETURN with [[nodiscard]]

include/charls/public_types.h, src/charls_jpegls_decoder.cpp, src/decoder_strategy.h, src/jpeg_stream_reader.cpp, src/jpeg_stream_reader.h, src/scan.h, unittest/decoder_strategy_test.cpp
Support to decode only certain regions has been removed. The only advantage was a smaller destination buffer and an optional quicker return. The JPEG-LS algorithm can only decoded starting from the beginning, so no real performance gain was made. Typical scenario is to decode complete image. If needed user code can perform a post processing step to extract a region is needed.
=> Remove legacy 1.x struct JlsRect

src/charls_jpegls_decoder.cpp, src/charls_jpegls_encoder.cpp, src/coding_parameters.h, src/jpeg_stream_reader.h, src/process_line.h, test/main.cpp
This was a Windows only option. Conversion is often not needed and Windows can do the conversion more efficient by itself. DirectX supports RGB encoded bitmaps.
=> Remove legacy 1.x option output_bgr

Directory.Build.props, test/bitstreamdamage.cpp, test/compliance.cpp, test/main.cpp, test/performance.cpp, test/portable_anymap_file.h, test/util.cpp, test/util.h, unittest/charls_jpegls_decoder_test.cpp, unittest/charls_jpegls_encoder_test.cpp, unittest/color_transform_test.cpp, unittest/compliance_test.cpp, unittest/decoder_strategy_test.cpp, unittest/documentation_test.cpp, unittest/encode_test.cpp, unittest/encoder_strategy_test.cpp, unittest/jpeg_stream_reader_test.cpp, unittest/jpeg_stream_writer_test.cpp, unittest/jpeg_test_stream_writer.h, unittest/jpegls_decoder_test.cpp, unittest/jpegls_encoder_test.cpp, unittest/util.cpp, unittest/util.h
C++17 introduced std::byte. Use it to replace uint8_t that was used as C++14 was lacking a byte type.
=> Replace uint8_t with std::byte in test projects

src/byte_span.h, src/decoder_strategy.h, src/encoder_strategy.h, src/jpeg_marker_code.h, src/jpeg_stream_reader.cpp, src/jpeg_stream_reader.h, src/jpeg_stream_writer.cpp, src/jpeg_stream_writer.h, src/scan.h
C++17 introduced std::byte. Use this type to define the buffers. In many cases continue to use uint8_t as often bytes values should be processed integers and not as a collection of 8 bits.
=> Use std::byte as type to define source/destination buffers

include/charls/charls_jpegls_decoder.h, include/charls/charls_jpegls_encoder.h, src/charls_jpegls_decoder.cpp, src/charls_jpegls_encoder.cpp, src/jpeg_stream_writer.cpp, src/jpegls.cpp, src/util.h, src/validate_spiff_header.cpp
Older compilers required additional qualifiers. With the C++ upgrade these are not longer needed.
=> Remove redundant qualifiers

.clang-tidy, src/conditional_static_cast.h, src/jpegls.cpp, src/lookup_table.h
This will move the 256 * 16 * 8 = 32768 bytes of the table from the .data section to the .rdata section.
=> Compute the Golomb decoding_tables at compile time.

include/charls/charls_jpegls_decoder.h, include/charls/charls_jpegls_encoder.h, src/jpegls.cpp, src/jpegls_preset_coding_parameters.h, src/scan.h
To prevent that overloads would have similar conversions, additional template parameters were introduced. Use these extra parameters to prevent warnings about not used template parameters. (C++20 concepts cannot be used)
=> Improve the SFINAE constructions: use template parameters

src/process_line.h, src/scan.h, src/util.h
- Remove not needed static_cast.
- if constexpr" is preferred to overloading for metaprogramming.
- Use std::byte instead of uint8_t when type is used as collection of bits and not as an integer value.
=> Resolve SonarQube warnings

src/jpegls.cpp, src/scan.h
As an initial step split the jls_coded into 2 classes.
This simplifies the templates and allows more efficient code generation.
Follow up commits are planned to move identical code to a shared base class.
=> Split jls_codec into scan_encoder/decoder_implementation

src/byte_span.h, src/charls_jpegls_decoder.cpp, src/charls_jpegls_encoder.cpp, src/encoder_strategy.h, src/jpeg_stream_reader.cpp, src/jpeg_stream_writer.cpp, src/jpeg_stream_writer.h, src/process_line.h, src/scan.h, src/util.h, unittest/decoder_strategy_test.cpp, unittest/encoder_strategy_tester.h, unittest/jpeg_stream_writer_test.cpp
const_byte_span is equal with C++20 std::span., byte_span was out of sync. Update byte_span to make it equal with std::span move the const_cast deeper into to the code to allow using const_byte_span in the encode call.
=> Update byte_span to be equal with std::span

src/charls_jpegls_encoder.cpp, src/decoder_strategy.h, src/encoder_strategy.h, src/jpeg_stream_reader.cpp, src/jpegls.cpp, src/scan.h, unittest/decoder_strategy_test.cpp, unittest/encoder_strategy_tester.h
The return value of create_process_line is only used by the scan_encoder/decoder class itself. Make it non-virtual and private.
=> Make create_process_line method non-virtual

src/default_traits.h, src/lossless_traits.h, src/scan_codec.h
C4127 = conditional expression is constant
C6326 = Potential comparison of a constant with another constant
C26814 = The const variable 'RANGE' can be computed at compile-time
With C++17 if constexpr the const template constructions can be indicated.
Note: some code needs to be duplicated as constexpr cannot be mixed with a runtime check.
=> Resolve MSVC warnings C4127, C6326 and C26814

src/scan_codec.h, src/scan_codec_factory.cpp, src/scan_codec_factory.h, src/scan_decoder_impl.h, src/scan_encoder_impl.h, unittest/scan_decoder_test.cpp, unittest/scan_encoder_test.cpp
De-duplicate scan_encoder_impl/scan_decoder_impl by moveing identical members to the base class.
=> Move non-template members to base class scan_codec

CharLS.sln, sonar-project.properties
- sonar.cfamily.cache.enabled is obsolete: remove it
- Only analyze the source code of the library
- Exclude the template source code file scan_decoder_impl and scan_encoder_imp. SonarCloud has problems to see that these are different files and cannot be merged.
=> Configure SonarCloud scope analysis

src/util.h
GCC\Clang provide 3 overloads for __builtin_clz:
int __builtin_clz (unsigned int x)
int __builtin_clzl (unsigned long)
int __builtin_clzll (unsigned long long)
GCC and Clang can be used to build CharLS for Linux\macOS (LP64 data model) and Windows (LLP64 data model).
Using __builtin_clzl (unsigned long) for 64 bits works for LP64 (long is 64 bits) but fails for the LLP64 data model (long is 32 bits) __builtin_clzll (unsigned long long) works for both the LP64 and the LLP64 data model (unsigned long long int is always at least 64 bits)
=> Fix countl_zero: replace __builtin_clzl with __builtin_clzll

CHANGELOG.md, include/charls/public_types.h, src/charls_jpegls_encoder.cpp, unittest/documentation_test.cpp, unittest/jpegls_encoder_test.cpp
3.0 is a major version and can contain breaking changes. Make include_pc_parameters_jai not default enabled. Java code that uses JAI is aware of this defect and decoders have workaround to prevent it. There is no need to enable this option by default during encoding anymore.
=> Make encoding_options::include_pc_parameters_jai not enabled by default

.clang-tidy, CharLS.sln.DotSettings, src/default_traits.h, src/process_decoded_line.h, src/process_encoded_line.h
Update the code to resolve warnings reported by the latest version of clang-tidy: Remove const for class members (class was never copied, but using const for data members is a-typical) Replace const reference data members with pointers (C++ core guidelines recommendation).
Due to many low level operations pointers are used a lot, disable the warning about unsafe buffers as this warning is not useful in our context.
=> Resolve clang-tidy warnings

.clang-tidy, CharLS.sln.DotSettings, default.ruleset, default.ruleset.md, include/charls/api_abi.h, src/conditional_static_cast.h, src/jpeg_marker_code.h, src/jpeg_stream_reader.cpp, src/lossless_traits.h, src/scan_codec.h, src/scan_encoder.h
- Exclude clang-tidy warning about C++14 (used C++ standard is now 17)
- Remove exclusion for false positive MSVC warning C26478 (fixed in 17.8.0)
- Grammar fixes
=> Update for Visual Studio 2022 17.8.0

include/charls/annotations.h, include/charls/api_abi.h, include/charls/charls.ixx, include/charls/charls_jpegls_decoder.h, include/charls/charls_jpegls_encoder.h, include/charls/jpegls_error.h, include/charls/public_types.h
Add a charls.ixx file that external project can include as a source file to import CharLS as a module like: import charls;
External projects need to include charls.ixx and compile it with their compiler settings and in C++20 mode or higher.
=> Add support to import CharLS as a C++20 module

.github/dependabot.yml
Github actions need to be updated from time to time. Use DependaBot to do this.
=> Add a dependabot configuration file for Github actions

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/msys2.yml
Github actions use the semver schema.
It is beter to only use the major version to make it possible to automatically pickup the latest version (instead of a specific tag). Upgrades of major versions are done useing dependabot
=> Use only the major version for Github actions

.clang-format, benchmark/benchmark.cpp, benchmark/context_regular_mode_v220.h, include/charls/charls_jpegls_decoder.h, include/charls/charls_jpegls_encoder.h, include/charls/jpegls_error.h, src/charls_jpegls_decoder.cpp, src/charls_jpegls_encoder.cpp, src/context_regular_mode.h, src/context_run_mode.h, src/default_traits.h, src/golomb_lut.h, src/jpeg_stream_reader.h, src/jpeg_stream_writer.h, src/jpegls_algorithm.h, src/jpegls_error.cpp, src/scan_codec.h, src/scan_codec_factory.cpp, src/scan_decoder.h, src/scan_decoder_impl.h, src/scan_encoder.h, src/scan_encoder_impl.h, src/span.h, src/util.h, test/portable_anymap_file.h, unittest/jpegls_decoder_test.cpp, unittest/scan_decoder_test.cpp, unittest/scan_encoder_tester.h, unittest/util.h
Follow the common cross language pattern to apply function attributes before the function definition/implementation.
This has mainly an impact on [[nodiscard]]
=> Update coding style (.clang-format) to BreakAfterAttributes: Always

src/charls_jpegls_decoder.cpp, src/charls_jpegls_encoder.cpp, src/make_scan_codec.cpp, src/make_scan_codec.h, src/scan_codec.h, src/scan_decoder.h, src/scan_decoder_impl.h, src/scan_encoder.h, src/scan_encoder_impl.h, unittest/scan_decoder_test.cpp, unittest/scan_encoder_tester.h
set_presets was used as a second constructor. Pass the pc_parameter to the base constructor to get rid of this method.
=> Replace set_presets with extra constructor parameter

src/color_transform.h, src/lossless_traits.h, src/process_decoded_line.h, src/process_encoded_line.h, src/scan_decoder.h, test/main.cpp
Background: a pixel consist of 1 or more samples. (RGB has 3 samples for example).
CharLS uses as SampleType a byte (uint8_t) or a 16 bit byte (uint16_t)
=> Rename all template parameters that indicate the type used to hold the sample to SampleType

CHANGELOG.md, include/charls/charls_jpegls_decoder.h, include/charls/charls_jpegls_encoder.h, src/jpeg_stream_reader.cpp, test/performance.cpp, unittest/documentation_test.cpp, unittest/jpegls_decoder_test.cpp, unittest/jpegls_encoder_test.cpp, unittest/util.cpp
Use helper methods to ensure const is correctly forwarded to the C API.
=> Update jpegls_decoder and jpegls_encoder to follow same const pattern as C API

CMakeLists.txt, README.md, src/jpeg_marker_code.h, src/jpeg_stream_reader.cpp, src/jpeg_stream_writer.cpp, src/jpegls_preset_parameters_type.h
Remove values from the enum that are only needed for slightly better error reporting (handle this locally)
Also add support matrix to readme
=> Simplify enums: only define used values

src/scan_decoder_impl.h
The line buffer is 2 pixels longer then required to make is easier to decode pixels on the edges. The start of the pointers was set to the first real pixel. This caused the problem that negative indexes needed to be used in the code, which looks incorrect at first sight and makes the code harder to port.
=> Use positive indexes to acces the line buffer during decoding

src/jpeg_stream_writer.cpp, src/jpeg_stream_writer.h, src/jpegls_algorithm.h, src/scan_codec.h, src/scan_decoder_impl.h, src/scan_encoder_impl.h, src/util.h, unittest/jpeg_stream_reader_test.cpp, unittest/jpeg_stream_writer_test.cpp, unittest/util.cpp
The line buffer is 2 pixels longer then required to make is easier to encode pixels on the edges. The start of the pointers was set to the first real pixel. This caused the problem that negative indexes needed to be used in the code, which looks incorrect at first sight and makes the code harder to port. The same was already done for the decoding process.
=> Use positive indexes to access the line buffer during encoding

CHANGELOG.md, include/charls/charls.h, include/charls/charls_jpegls_encoder.h, include/charls/jpegls_error.h, include/charls/public_types.h, spelling.dic, src/charls_jpegls_decoder.cpp, src/charls_jpegls_encoder.cpp, src/jpeg_stream_reader.cpp, src/jpeg_stream_reader.h, src/jpeg_stream_writer.cpp, src/jpeg_stream_writer.h, src/jpegls_error.cpp, src/regular_mode_context.h, src/scan_decoder.h, src/scan_decoder_impl.h, src/scan_encoder.h, src/util.h, test/bitstreamdamage.cpp, test/main.cpp, unittest/charls_jpegls_decoder_test.cpp, unittest/charls_jpegls_encoder_test.cpp, unittest/jpeg_stream_reader_test.cpp, unittest/jpeg_stream_writer_test.cpp, unittest/jpegls_decoder_test.cpp, unittest/jpegls_encoder_test.cpp
Group the error IDs in errors that cannot be prevented and can be reported at runtime and in a set of errors that can be prevented.
Note 1: the error destination_too_small is considerd a runtime failure, but can in many cases be prevented.
Note 2: unexpected exceptions will now trigger a call to std::terminate (improved crash dumps)
=> Re-order the failure values of the enum jpegls_errc (breaking change)

CharLS.sln.DotSettings, include/charls/charls_jpegls_decoder.h, include/charls/jpegls_decoder.hpp, include/charls/public_types.h, src/charls_jpegls_decoder.cpp, src/jpeg_stream_reader.cpp, src/jpeg_stream_reader.hpp, unittest/jpegls_decoder_test.cpp, unittest/util.hpp
The JPEG-LS standard defines 3 compressed data formats. Only the interchange format (the most common) can normally be decoded. Add a method to allow application code to retrieve the data format of the JPEG-LS stream. This allows an application to decide if it want to display the image or process it differently.
=> Add method charls_decoder_get_compressed_data_format

benchmark/benchmark.cpp, benchmark/benchmark.vcxproj, benchmark/benchmark.vcxproj.filters, benchmark/decode.cpp, benchmark/golomb_lut_constexpr.cpp, src/charls_jpegls_decoder.cpp, src/golomb_lut.hpp, src/jpegls_algorithm.hpp, src/run_mode_context.hpp, src/scan_decoder.hpp, src/scan_decoder_impl.hpp, src/scan_encoder_impl.hpp, unittest/charls_jpegls_encoder_test.cpp, unittest/color_transform_test.cpp, unittest/golomb_table_test.cpp, unittest/jpegls_decoder_test.cpp, unittest/run_mode_context_test.cpp, unittest/scan_decoder_test.cpp
The main purpose of golomb_code_match is to see if there is a precomputed match which allows to just skip the bytes. Rename the struct to make it clear it is not the actual glomb code itself. Update the golomb_code_match struct back into a POD. The Windows x64 ABI cannot return non-POD structs in a single register even when the would fit.
=> Update the name of golomb_code to golomb_code_match and POD conversion

src/default_traits.hpp, src/lossless_traits.hpp, src/make_scan_codec.cpp, src/make_scan_codec.hpp, src/run_mode_context.hpp, src/scan_codec.hpp, src/scan_decoder.hpp, src/scan_decoder_impl.hpp, src/scan_encoder_impl.hpp, test/main.cpp, unittest/default_traits_test.cpp, unittest/lossless_traits_test.cpp, unittest/run_mode_context_test.cpp, unittest/scan_encoder_test.cpp
reset_threshold is just a parameter. Remove it from the traits class to have more flexibility.
=> Move processing of restart marker to base class + reset_threshold

src/jpeg_stream_reader.cpp, src/jpeg_stream_reader.hpp, unittest/jpeg_stream_reader_test.cpp, unittest/jpeg_test_stream_writer.hpp, unittest/jpegls_decoder_test.cpp
Section ISO/IEC 14495-1, C.2.6 specifies that JPEG-LS allows DNL segments with a length between 4 and 6 bytes. Update the code to handle these DNL segments.
=> Add support for DNL segments with lines > 2^16 (#59)

.clang-tidy, src/charls_jpegls_decoder.cpp, src/copy_from_line_buffer.hpp, src/copy_to_line_buffer.hpp, src/default_traits.hpp, src/jpeg_stream_reader.cpp, src/lossless_traits.hpp, src/make_scan_codec.cpp, src/scan_decoder_impl.hpp, src/scan_encoder_impl.hpp, src/util.hpp, unittest/encode_test.cpp
2 components in interleave mode none was already supported. But the options line and sample were not implemented. Add these 2 options to support all interleave options.
=> Add support to encode and decode 2 components by line and sample

CHANGELOG.md, README.md, include/charls/charls_jpegls_decoder.h, include/charls/charls_jpegls_encoder.h, include/charls/jpegls_decoder.hpp, include/charls/jpegls_encoder.hpp, src/charls_jpegls_decoder.cpp, src/charls_jpegls_encoder.cpp, src/constants.hpp, src/jpeg_stream_reader.cpp, src/jpeg_stream_reader.hpp, test/compliance.cpp, test/main.cpp, unittest/charls_jpegls_decoder_test.cpp, unittest/compliance_test.cpp, unittest/documentation_test.cpp, unittest/encode_test.cpp, unittest/jpeg_stream_reader_test.cpp, unittest/jpegls_decoder_test.cpp, unittest/jpegls_encoder_test.cpp, unittest/util.cpp
Add an additional method for advanced encodings scenarios. This methods allow to encode components with different coding parameters like: near lossless, jpeg-ls preset coding parameters or scans with different interleave modes. Extend the decoder to also be able to decode scans with different interleave modes.
=> Extend API of jpeg_encoder with encode_components methods

CMakeLists.txt, src/CMakeLists.txt, src/make_scan_codec.cpp, src/make_scan_codec.hpp, src/scan_decoder_impl.hpp
- Remove code from make_scan_codec that was not used
- Unsure that undef_macro.h file is added to the list of public headers in CMakeLists.txt
=> Remove duplicate code from make_scan_codec + undef_macros.h

CHANGELOG.md, CMakeLists.txt, Directory.Build.props, doc/style_and_design.md, src/CMakeLists.txt, unittest/CodeCoverage.runsettings
Some of these files might have been automatically generated. Should typos be fixed upstream instead?
=> Fix typos found by codespell

.clang-tidy, default.ruleset, default.ruleset.md, include/charls/public_types.h
- The MSVC warning C26493 was broken in VS 2022 17.11. It has been fixed in 17.12
- Update .clang-tidy. Disable new but not useful warnings.
=> Re-enable warning C26493

benchmark/benchmark.cpp, benchmark/benchmark.vcxproj, benchmark/golomb_lut_constexpr.cpp, benchmark/vcpkg.json, cpp.hint, spelling.dic
vcpkg requires lowercase triplet names. Using ARM64 will trigger a failure. Add an explicit override to resolve this.
=> Fix triplet problem with vcpkg and ARM64 platform

.editorconfig, src/CMakeLists.txt, src/CharLS.vcxproj, src/CharLS.vcxproj.filters, src/charls.rc, src/charls_jpegls_decoder.cpp, src/charls_jpegls_encoder.cpp, src/coding_parameters.hpp, src/golomb_lut.cpp, src/jpeg_stream_reader.cpp, src/jpeg_stream_reader.hpp, src/jpeg_stream_writer.cpp, src/jpeg_stream_writer.hpp, src/jpegls_error.cpp, src/jpegls_preset_coding_parameters.hpp, src/make_scan_codec.cpp, src/pch.cpp, src/pch.hpp, src/quantization_lut.cpp, src/scan_decoder.hpp, src/util.hpp, src/validate_spiff_header.cpp, src/version.cpp, unittest/CharLSUnitTest.vcxproj
All modern C++ compiler support precompiled headers, add one to increase build performance.
=> Add precompiled header

.clang-tidy, CMakeLists.txt, azure-pipelines.yml, fuzzing/afl/main.cpp, samples/convert.c/main.c, src/CMakeLists.txt, src/CharLS.vcxproj, src/CharLS.vcxproj.filters, src/assert.hpp, src/charls_jpegls_decoder.cpp, src/charls_jpegls_encoder.cpp, src/constants.hpp, src/default_traits.hpp, src/jpegls_algorithm.hpp, src/span.hpp, src/util.hpp, test/main.cpp, test/util.cpp, unittest/jpeg_test_stream_writer.hpp, unittest/util_test.cpp
Newer versions of clang-tidy support a configuration format, that allows to have the rationals inline when a warning is disabled.
Switch to this configuration format and also only not all warnings, but only the standard and useful warning groups.
Many warning group are designed for a specific project and are not univeral usable.
=> Clean up the .clang-tidy configuration file
